#!/bin/bash
cd /home/venkman/git/iptv
pidfile='.iptvdlmgr.pid'
killpid(){
    if [ -f $pidfile ]
    then
        psid=`cat $pidfile`
        kill  $psid
        if [ $? -eq 0 ]
        then
            echo "Process killed"
            rm $pidfile
        else
            echo "Process did not die"
            exit 1
        fi
    fi
}
checkpid(){
    if [ -f $pidfile ]
    then
        psid=`cat $pidfile`
        ps -p $psid >/dev/null
        if [ $? -eq 0 ]
        then
            echo "Process is still running"
            exit
        fi
    fi
}
makevenv(){
    if [ ! -d venv ]
    then
        python3 -m venv venv
    fi
}
rebuild() {
    killpid
    git pull
    rm -rf venv
    start
}

start(){

    makevenv
    checkpid
    git pull
    . ./venv/bin/activate
    pip install -r requirements.txt
    ./venv/bin/python download_mgr.py &
    echo $! > $pidfile

}

if [ "$1" = "stop" ]
then
    killpid
    exit
fi
{
    if [ "$1" = "restart" ]
    then
        killpid
    fi
    if [ "$1" = "makevenv" ]
    then
        makevenv
    fi
    if [ "$1" = "rebuild" ]
    then
        rebuild
    fi

    start

}>>rundlmgr.log 2>&1

